Домашнее задание №2
Frontend-Sirius-VK/2022-autumn-a.motrikala pull request #2
Opened 2022-12-02 22:35 UTC by dancinginthedarkk

2022-12-05 22:02 UTC, StealthTech requested changes
- Картинки стоит выносить в отдельную папку assets либо assets/images на каждом уровне. 
- Стоит сделать скрипт для наполнения базы какими-нибудь тестовыми данными
- Можешь, плиз, прикрепить скрин, как выглядит проект с подключением к базе?

2022-12-05 22:02 UTC, StealthTech commented on .env
> +APP_PORT=3050
Стоит ставить в конце файла перенос строки https://semakin.dev/2020/05/no_newline_at_end_of_file/ — справедливо для всех файлов

2022-12-05 22:02 UTC, StealthTech commented on components/header/header.css
> +.header{
Не забываем ставить пробел между селектором и скобкой

2022-12-05 22:02 UTC, StealthTech commented on components/header/header.css
> +img{
По тегу лучше не делать стилизацию

2022-12-05 22:02 UTC, StealthTech commented on components/header/header.css
> +    width: 758px;
Стоит избегать конкретной ширины в пикселях с не-круглыми числами для любых элементов кроме картинок (например, 750px — ok, 758px - not ok)

2022-12-05 22:02 UTC, StealthTech commented on components/header/header.js
> +        main_icon.src = './components/header/Dzen_logo.png';
Лучше переименовать файл в dash-case. Например, `dzen-logo.png` — так будет лучше читаться

2022-12-05 22:02 UTC, StealthTech commented on components/header/header.js
> +        main_icon.alt = 'Dzen_icon';
Атрибут alt должен содержать понятное человекочитаемое описание — он нужен на случай, если картинка не прогрузилась или у устройства вообще нет экрана (устройство для слабовидящих)

2022-12-05 22:02 UTC, StealthTech commented on components/header/header.js
> +        const main_icon = document.createElement('img');
Переменные и константы в JavaScript принято называть в camelCase — тут чувствуется след питониста

2022-12-05 22:02 UTC, StealthTech commented on components/header/header.js
> +    }
Очень рекомендую переписать на handlebars

2022-12-05 22:02 UTC, StealthTech commented on components/postCard/postCard.js
> +    render(author_data, subscribes_data, header_data, post_url, content_data, img_url, published_data) {
здесь можно принимать объект и сразу его деструктуризировать, чтобы не нужно было иметь 7 аргументов

2022-12-05 22:02 UTC, StealthTech commented on components/postCard/postCard.js
> +        const info_text = document.createElement('div');
Поправить везде на camelCase

2022-12-05 22:02 UTC, StealthTech commented on components/postCard/posts.css
> +    background: #FFFFFF;
Цвета стоит вынести в CSS Custom Properties в какой-нибудь файл с палитрой

2022-12-05 22:02 UTC, StealthTech commented on components/postCard/posts.css
> +    color: rgba(0,0,0,.45);
Пробельчиков не хватает

2022-12-05 22:02 UTC, StealthTech commented on components/postCard/posts.css
> +    /*padding: 2px 18px 0;*/
Закомментированный код в продакшен не должен попадать

2022-12-05 22:02 UTC, StealthTech commented on components/postCard/posts.css
> +.img_div {
В этом ДЗ не обязательно, но к следующему надо причесать все классы в БЭМ

2022-12-05 22:02 UTC, StealthTech commented on components/postCardRender/postCardRender.js
> +        data.forEach((post) =>{
Пробел

2022-12-05 22:02 UTC, StealthTech commented on components/postCardRender/postCardRender.js
> +           postCard.render(post.author, post.subscribers, post.header, post.post_url, post.content, post.img_url, post.published);
Если сделать функцию render принимающей объект, то можно будет просто postCard.render(post)

2022-12-05 22:02 UTC, StealthTech commented on main.css
> +@import 'components/postCard/posts.css';
Давай сделаем, чтобы импорты были в одном стиле — с точкой или без

2022-12-05 22:02 UTC, StealthTech commented on models/postModel.js
> +    constructor(author = null, subscribers = null, header = null, post_url = null, content = null, img_url = null, published = null){
Тоже можно деструктуризацией

2022-12-05 22:02 UTC, StealthTech commented on models/postModel.js
> +            console.log('Posts ::', data);
В реальном коде так не делаем никогда — не должно выводиться в консоль отладочной информации

2022-12-05 22:02 UTC, StealthTech commented on models/postModel.js
> +        fetch('/posts').then((response) => response.json()).then((data) => {
Место для деструктуризации data

2022-12-05 22:02 UTC, StealthTech commented on routing/Router.js
> +        // if (tagName === 'A') {
Почему?

2022-12-05 22:02 UTC, StealthTech commented on server.js
> +app.get('/posts', async (req,res) => {
По заданию нужно было реализовать не только получение списка постов, но и создание/изменение/удаление поста

2022-12-06 11:27 UTC, dancinginthedarkk commented
так выглядит проект с подключенной бд:
![Снимок экрана от 2022-12-03 15-00-44](https://user-images.githubusercontent.com/91607846/205899593-314b2ef9-885d-4da8-ac41-773a0859b8f2.png)

2022-12-06 11:30 UTC, dancinginthedarkk commented on server.js
> +app.get('/posts', async (req,res) => {
это же вроде бы задание на след неделю...

2022-12-06 18:14 UTC, StealthTech commented on server.js
> +app.get('/posts', async (req,res) => {
Да, ты права — в этом ДЗ не требуется

2022-12-07 13:53 UTC, StealthTech approved these changes

2022-12-07 13:53 UTC, merged