Домашнее задание №3
Frontend-Sirius-VK/2022-autumn-a.motrikala pull request #3
Opened 2022-12-10 13:18 UTC by dancinginthedarkk

2022-12-10 13:20 UTC, dancinginthedarkk commented
![Снимок экрана от 2022-12-10 16-10-57](https://user-images.githubusercontent.com/91607846/206857292-72b0b849-7933-4629-aef9-b28e2dcef9f3.png)
![Снимок экрана от 2022-12-10 16-11-10](https://user-images.githubusercontent.com/91607846/206857295-d123d148-f3ac-465e-a3b1-035a3c9bc557.png)
![Снимок экрана от 2022-12-10 16-11-24](https://user-images.githubusercontent.com/91607846/206857297-5346b999-e52a-4323-a2e6-d3f9ec7ed8eb.png)

2022-12-14 20:14 UTC, Betchika99 requested changes
- [ ] баг - при навигации через стрелку Назад в браузере со страницы одного поста меняется только урл, а контент страницы остается прежним
- [ ]  на сервере нет обработки ошибок, т.е. статусы, которые ты проверяешь на фронте, никогда не будут проставлены (да-да, их надо ручками проставлять на сервере). можно проверить просто - отключаешь базу и пробуешь открыть свой сайт. должна быть ошибка, а у тебя сейчас белый экран
- [x] желательно, чтобы обработчик app.listen был в самом конце файла, чтобы его было просто найти и он не затерялся среди остальных обработчиков запросов
- [ ] проверить корректность возвращаемых кодов ответа по ручкам создания/изменения/удаления сущности Пост
- [ ] ни в одном обработчике на сервере нет валидации данных (что данные действительно пришли с фронта корректные)
- [ ] не проверяется, что все необходимые поля для отрисовки, пришли с бекенда. например, если бек не прислал title, то будет такая ситуация
![image](https://user-images.githubusercontent.com/34346716/207703865-81c70a15-e2c3-40ca-be58-e839907f9243.png)

про адаптив: лучше оставлять больше воздуха по бокам в мобильном виде
![image](https://user-images.githubusercontent.com/34346716/207704484-42f7dea9-1a5c-4a2d-abe2-fdefe6d6ba8f.png)

**Дедлайн на исправления: пятница 16.12 23:59**

2022-12-14 20:14 UTC, Betchika99 commented on server.js
> +app.get('/post/:id', async (req,res) => {
урлы для сущностей называем по rest. и для роутинга на фронтенде, и для урлов на бекенде. здесь должен быть **/posts/:id**

2022-12-14 20:14 UTC, Betchika99 commented on server.js
> +app.get('/getPostById/:id', async (req,res) => {
здесь тоже по REST-у должен быть урл /posts/:id , но этот урл будет конфликтовать с фронтовым. в дз4 у тебя это починится с помощью вебпака, а пока что можно оставить TODO "переделать на REST". или, если интересно, можешь добавить subrouter (это не сложно и не долго, пример [тут](https://stackoverflow.com/questions/25260818/rest-with-express-js-nested-router))

2022-12-14 20:14 UTC, Betchika99 commented on server.js
> +    const result = await db.getPostById(id);
async/await обязательно оборачиваем в try/catch (иначе потеряем исключения!). здесь и далее

2022-12-14 20:14 UTC, Betchika99 commented on queries.js
> +        return result.rows[0].id
а если нет rows? тут будет исключение. посмотри в сторону [optional chaining](https://learn.javascript.ru/optional-chaining)

2022-12-14 20:14 UTC, Betchika99 commented on queries.js
> +        return result.rows[0];
а если нет rows? тут будет исключение

2022-12-14 20:14 UTC, Betchika99 commented on queries.js
>  }
во всем файле потеряны точки с запятой в конце строк

2022-12-14 20:14 UTC, Betchika99 commented on queries.js
> +        console.log(error)
фронт об этом никогда не узнает :( здесь и в остальных местах

2022-12-14 20:14 UTC, Betchika99 commented on server.js
> +    const { author, subscribers, title, postUrl, contentData, imgUrl, published } = req.body;
нет проверки, что все эти поля были переданы в body. может быть исключение при работе с базой

2022-12-14 20:14 UTC, Betchika99 commented on server.js
> +    res.json({id})
код ответа не правильный

2022-12-14 20:14 UTC, Betchika99 commented on server.js
> +    const { id, author, subscribers, title, postUrl, contentData, imgUrl, published } = req.body;
нет проверки, что все эти поля были переданы в body. может быть исключение при работе с базой

2022-12-14 20:14 UTC, Betchika99 commented on server.js
> +    res.json({result});
метод delete не возвращает тело

2022-12-14 20:14 UTC, Betchika99 commented on routing/Router.js
> +    }
хорошо списывает тот, кто понимает ошибки) эта функция не нужна. айди можно получить с помощью той же регулярки в функции invokeController

2022-12-14 20:14 UTC, Betchika99 commented on routing/Router.js
> +        const pathname = window.location.pathname;
лучше через деструктуризацию

2022-12-14 20:14 UTC, Betchika99 commented on routing/Router.js
> +            return matches;
return Boolean(matches), иначе может быть проблема

2022-12-14 20:14 UTC, Betchika99 commented on routing/Router.js
> +        }
это кому лог? показываем страницу ошибки 404

2022-12-14 20:14 UTC, Betchika99 commented on routing/Router.js
> +        controller.process(id);
не всем контроллерам нужен id в process, нужно добавить какой-то флаг и проверку перед вызовом этого метода с параметром

2022-12-14 20:14 UTC, Betchika99 commented on controllers/PostController.js
> +import {onePostModel} from '../models/onePostModel.js';
зачем "one"? PostModel и так понятно, что модель одного поста :)

2022-12-14 20:14 UTC, Betchika99 commented on components/header/header.js
> +        buttonCreate.href = CREATE_POST;
здесь и далее с другими внешними ссылками - когда мы уводим пользователя с нашего ресурса на какой-то внешний, лучше добавлять ссылкам атрибут target=_blank. тогда пользователь не потеряет ссылку с нашим приложением, потому что внешняя страница откроется в новой вкладке

2022-12-14 20:14 UTC, Betchika99 commented on components/header/header.css
> +    .header-controls-create-button, .header-controls-video-button, .header-controls-search-button {
такие длинные строки не круто, лучше написать в столбик:

.header-controls-create-button,  
.header-controls-video-button,  
.header-controls-search-button {

2022-12-14 20:14 UTC, Betchika99 commented on components/header/header.css
> +    .header-controls-create-button, .header-controls-video-button, .header-controls-search-button {
а тебе точно нужны три разных класса здесь? если они никак не переопределяются и всегда используются одинаково, зачем дублировать код?

2022-12-14 20:14 UTC, Betchika99 commented on components/loader/loader.css
> +    color: rgba(192, 192, 192, .5);
выносим цвета в css переменные

2022-12-14 20:14 UTC, Betchika99 commented on components/loader/loader.css
> +}
![image](https://user-images.githubusercontent.com/34346716/207701946-afe12b10-abca-447a-9dc6-3d94f034f819.png)

желательно здесь лоадер отцентровать по вертикали (например, только в этом случае навешивать контейнеру какой-то класс, который позволит лоадеру встать по центру)

2022-12-14 20:14 UTC, Betchika99 commented on components/onePostCard/onePost.css
> +.card-text{
пробел перед { потерялся

2022-12-14 20:14 UTC, Betchika99 commented on components/postCard/postCard.js
> +        headerText.href = `/post/${id}`;
по ресту урл должен быть /posts/id

2022-12-14 20:14 UTC, Betchika99 commented on models/onePostModel.js
> +                }
этот код вряд ли когда-то выполнится, т.к. на сервере нет таких обработчиков. здесь и далее

2022-12-14 20:14 UTC, Betchika99 commented on models/onePostModel.js
> +                    EventBus.emit('onePostCard:bad-request', ['Ошибка 400', 'Вы ввели некорректный запрос, проверьте данные.']);
а зачем для ошибок разные события? ты же все равно передаешь текстом, в чем проблема + обрабатываешь события одинаково. можно и одним событием обойтись

2022-12-14 20:14 UTC, Betchika99 commented on models/onePostModel.js
> +                    EventBus.emit('onePostCard:bad-request', ['Ошибка 400', 'Вы ввели некорректный запрос, проверьте данные.']);
лучше возвращать не массив строк, а объект. типа {title: ... , description: ...}

2022-12-14 20:14 UTC, Betchika99 commented on views/MainView.js
> +    }
можно наверно без этого метода. просто использовать renderError, потому что ошибка по дефолту у тебя здесь никогда рисоваться не будет

2022-12-14 20:14 UTC, Betchika99 commented on views/MainView.js
> +        const root = document.querySelector('#root');
дубль кода с методом render. мб вынесем в конструктор и положим в поле класса?

2022-12-14 20:14 UTC, Betchika99 commented on views/MainView.js
> +        root.append(this.container);
![image](https://user-images.githubusercontent.com/34346716/207703140-094ec43c-6198-48a4-873c-f85c307a36dd.png)

при такой реализации над ошибкой будет крутиться бесконечный лоадер. надо его убирать не только, когда данные пришли, но и когда ошибка произошла

2022-12-14 20:14 UTC, Betchika99 commented on views/MainView.js
> +        root.append(this.container);
ошибки тоже лучше центровать по вертикали (см. аналогичный коммент про лоадер)

2022-12-14 20:14 UTC, Betchika99 commented on components/onePostCard/onePost.css
> +}
картинку надо как-то по размерам ограничивать (но при этом, чтобы она не была сплюснутой). иначе кто-то может загрузить в пост картинку огромных размеров и твоя верстка поедет

2022-12-15 15:30 UTC, dancinginthedarkk commented on components/loader/loader.css
> +}
переделала
![Снимок экрана от 2022-12-15 18-29-07](https://user-images.githubusercontent.com/91607846/207900949-e5219dd0-a7f7-4c05-a558-03de28c44f30.png)

2022-12-15 15:31 UTC, dancinginthedarkk commented on components/loader/loader.css
> +}
переделала
![Снимок экрана от 2022-12-15 18-30-54](https://user-images.githubusercontent.com/91607846/207901246-884ade49-8ddb-4fb3-9b4f-4958c3ebc807.png)

2022-12-15 16:08 UTC, dancinginthedarkk commented on views/MainView.js
> +        root.append(this.container);
убрала
![Снимок экрана от 2022-12-15 19-07-34](https://user-images.githubusercontent.com/91607846/207910069-8d47b4bc-290d-48f9-8c31-da892db6fa61.png)

2022-12-15 16:09 UTC, dancinginthedarkk commented on views/MainView.js
> +        root.append(this.container);
![Снимок экрана от 2022-12-15 19-09-13](https://user-images.githubusercontent.com/91607846/207910387-3d487c57-9465-4cd3-be32-347ce2813c35.png)

2022-12-15 16:43 UTC, dancinginthedarkk commented
про мобильную верстку: добавила воздуха
![Снимок экрана от 2022-12-15 19-42-20](https://user-images.githubusercontent.com/91607846/207918272-e81e1c85-b926-43d0-bf83-4e9793d02bac.png)

2022-12-15 19:32 UTC, dancinginthedarkk commented on components/onePostCard/onePost.css
> +}
я в самой карточке говорю, какую ожидаю высоту, поэтому все ок

2022-12-16 19:00 UTC, Betchika99 approved these changes

2022-12-16 19:00 UTC, merged